### ISSUE TITLE
runtest fails with `ImportError: No module named psutil`

### ISSUE THREAD

**Issue by digitarald** [Mozilla-TWQA/Hasal#358]
After #357 my installation can't run tests even though logs show that `psutil` got installed.

``` bash
> python runtest.py re suite.txt
Traceback (most recent call last):
  File "runtest.py", line 27, in <module>
    from lib.helper.uploadAgentHelper import UploadAgent
  File "/Users/hkirschner/Sites/Hasal/lib/helper/uploadAgentHelper.py", line 7, in <module>
    import desktopHelper
  File "/Users/hkirschner/Sites/Hasal/lib/helper/desktopHelper.py", line 7, in <module>
    from ..browser.chrome import BrowserChrome
  File "/Users/hkirschner/Sites/Hasal/lib/browser/chrome.py", line 1, in <module>
    from base import BrowserBase
  File "/Users/hkirschner/Sites/Hasal/lib/browser/base.py", line 2, in <module>
    import psutil
ImportError: No module named psutil
```

**Comment by ShakoHo** [comment]
Hi Harald,

  It seems you are not get into the python virtual environment.

  Please execute the command below under Hasal working directory before having the runtest.py executed.

  "source .env-python/bin/activate"

**Comment by digitarald** [comment]
That fixed it
